version: '3'

services:
  mysql:
    image: mysql:latest
    restart: unless-stopped
    tty: true
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=ignite-call
      - MYSQL_USER=ignite
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
    volumes:
      - ./database:/var/lib/mysql
